In [39]:
import numpy as np

In [40]:
np1 = np.array([1,2,3,4,5,6])
np2 = np.array([[1,2,3],[4,5,6]])
np1 

array([1, 2, 3, 4, 5, 6])

In [41]:
np2

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
np3 = np.array((1,2,'3'))
np3

array(['1', '2', '3'], dtype='<U11')

In [43]:
np4=np.zeros((3,4))
np4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
np5=np.ones((3,4))
np5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
np6=np.empty((3,4))
np6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
np.arange(1,20,.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5])

In [47]:
list(i for i in range(1,20,5))

[1, 6, 11, 16]

In [48]:
np.linspace(1,20,100) #可以取到20.但是range和arange取不到

array([ 1.        ,  1.19191919,  1.38383838,  1.57575758,  1.76767677,
        1.95959596,  2.15151515,  2.34343434,  2.53535354,  2.72727273,
        2.91919192,  3.11111111,  3.3030303 ,  3.49494949,  3.68686869,
        3.87878788,  4.07070707,  4.26262626,  4.45454545,  4.64646465,
        4.83838384,  5.03030303,  5.22222222,  5.41414141,  5.60606061,
        5.7979798 ,  5.98989899,  6.18181818,  6.37373737,  6.56565657,
        6.75757576,  6.94949495,  7.14141414,  7.33333333,  7.52525253,
        7.71717172,  7.90909091,  8.1010101 ,  8.29292929,  8.48484848,
        8.67676768,  8.86868687,  9.06060606,  9.25252525,  9.44444444,
        9.63636364,  9.82828283, 10.02020202, 10.21212121, 10.4040404 ,
       10.5959596 , 10.78787879, 10.97979798, 11.17171717, 11.36363636,
       11.55555556, 11.74747475, 11.93939394, 12.13131313, 12.32323232,
       12.51515152, 12.70707071, 12.8989899 , 13.09090909, 13.28282828,
       13.47474747, 13.66666667, 13.85858586, 14.05050505, 14.24

In [49]:
my_dict = {'a': (1, 2), 'b': (3, 4), 'c': (5, 6)}
my_array = np.array(list(my_dict.values()))
my_array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
my_dict = {'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]}
my_array = np.array(list(my_dict.values()))
my_array = np.vstack(my_array)

In [51]:
my_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
my_dict = {'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]}
my_array = np.array(my_dict.items())

print(my_array)

dict_items([('a', [1, 2, 3]), ('b', [4, 5, 6]), ('c', [7, 8, 9])])


In [53]:
my_array.dtype.name

'object'

In [54]:
np1_float = np1.astype(np.float64)

In [55]:
np1_float

array([1., 2., 3., 4., 5., 6.])

In [56]:
#np7 = np.array(['1','2','a'])
#np7.astype([np.int64,np.int64,np.object])
#np7

## 矢量化运算

In [57]:
data1  = np.array([[1,2,3],[4,5,6]])
data2  = np.array([[1,2,3],[4,5,6]])
data1

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
data2

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
data1+data2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [60]:
data1*data2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [61]:
data1/data2  #数组相除时得到的结果是浮点数

array([[1., 1., 1.],
       [1., 1., 1.]])

In [62]:
data1-data2

array([[0, 0, 0],
       [0, 0, 0]])

## 数组广播

In [63]:
arr1 = np.array([[1],[2],[3],[4]])
arr1.shape

(4, 1)

In [64]:
arr2 = np.array([1,2,3])
arr2.shape

(3,)

In [65]:
arr1+arr2

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

In [66]:
arr1

array([[1],
       [2],
       [3],
       [4]])

In [67]:
arr2

array([1, 2, 3])

## 数组与标量之间的运算

In [68]:
s1 = np.array([[1,2,3],[4,5,6]])
s1+10

array([[11, 12, 13],
       [14, 15, 16]])

In [69]:
s1*10

array([[10, 20, 30],
       [40, 50, 60]])

In [70]:
s1/10

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6]])

In [71]:
s1-10

array([[-9, -8, -7],
       [-6, -5, -4]])

In [72]:
s1*10-10

array([[ 0, 10, 20],
       [30, 40, 50]])

## 索引和切片的使用

In [73]:
arr = np.array([0,1,2,3,4,5,6,7])
arr[3]

3

In [74]:
arr[0:6] #左闭右开取不到最后一个

array([0, 1, 2, 3, 4, 5])

In [75]:
arr[0:8:2]

array([0, 2, 4, 6])

In [76]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[1]

array([4, 5, 6])

In [77]:
arr2d[1,1]

5

In [78]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
arr2d[:2]  #前两行

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
arr2d[:2,:2] #前两行前两列相交位置的元素

array([[1, 2],
       [4, 5]])

In [81]:
arr2d[:,0]#某一列元素

array([1, 4, 7])

In [82]:
arr2d[:]  #拷贝数组

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 花式索引

In [83]:
demo_arr = np.empty((4,4))
for i in range (4):
    demo_arr[i]=np.arange(i,i+4)
demo_arr

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.]])

In [84]:
demo_arr[[0,2]]

array([[0., 1., 2., 3.],
       [2., 3., 4., 5.]])

In [85]:
demo_arr[[0,1],[0,1]]

array([0., 2.])

## 布尔型索引

In [86]:
student_name=np.array(['tom','jack','rose','lily'])
student_score=np.array([[79,88,80],[89,90,82],[83,78,85],[73,76,80]])

In [87]:
student_name=='jack'

array([False,  True, False, False])

In [88]:
student_score[student_name=='jack'] #返回的是里面表达式中为true位置上的索引在student_score 上对应的值

array([[89, 90, 82]])

In [89]:
student_score[student_name=='jack',:1]#布尔型索引与切片的混合使用

array([[89]])

## 数组的转置

In [90]:
arr_a = np.arange(12).reshape(3,4)
arr_a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
arr_a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [92]:
arr_a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
arr_b = np.arange(16).reshape((2,2,4))
arr_b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [94]:
arr_b.transpose(1,2,0)

array([[[ 0,  8],
        [ 1,  9],
        [ 2, 10],
        [ 3, 11]],

       [[ 4, 12],
        [ 5, 13],
        [ 6, 14],
        [ 7, 15]]])

In [95]:
arr_b.transpose()  #等价于transpose(2,1,0)

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

## numpy通用函数

In [96]:
arr_1 = np.array([1,2,3])
np.sqrt(arr_1)

array([1.        , 1.41421356, 1.73205081])

In [97]:
np.square(arr_1)

array([1, 4, 9])

In [98]:
x=np.array([12,9,13,15])
y=np.array([11,10,4,8])
np.add(x,y)

array([23, 19, 17, 23])

In [100]:
np.multiply(x,y)

array([132,  90,  52, 120])

In [101]:
np.maximum(x,y)

array([12, 10, 13, 15])

In [102]:
np.greater(x,y)

array([ True, False,  True,  True])

## 将条件逻辑转化为数组运算

In [103]:
arr_x = np.array([1,5,7])
arr_y = np.array([2,6,8])
arr_con=np.array([True,False,True])
result = np.where(arr_con,arr_x,arr_y)
result

array([1, 6, 7])

## 数组的统计运算

In [107]:
arrnum=np.arange(10)

In [106]:
arrnum.sum()

45

In [108]:
arrnum.cumsum()#计算每个元素的累计和

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [109]:
arrnum.mean()

4.5

In [110]:
arrnum.min()

0

In [111]:
arrnum.max()

9

In [112]:
arrnum.argmax()

9

In [113]:
arr.cumprod()#计算所有元素的累积

array([0, 0, 0, 0, 0, 0, 0, 0])

## 数组排序

In [114]:
arr_sort=np.array([[6,2,7],[3,6,2],[4,3,2]])
arr_sort.sort() 

In [115]:
arr_sort

array([[2, 6, 7],
       [2, 3, 6],
       [2, 3, 4]])

In [116]:
arr_sort2=np.array([[6,2,7],[3,6,2],[4,3,2]])
arr_sort2.sort(0)

In [117]:
arr_sort2

array([[3, 2, 2],
       [4, 3, 2],
       [6, 6, 7]])

## 检索数组元素

In [119]:
arr_search=np.array([[1,-2,-7],[-3,6,2],[-4,3,2]])
np.any(arr_search>0)

True

In [120]:
np.all(arr_search>0)

False

In [121]:
arr_search.sum(0)

array([-6,  7, -3])

## 唯一化及其他逻辑

In [123]:
arr_only=np.array([12,11,34,23,12,8,11])
np.unique(arr_only)

array([ 8, 11, 12, 23, 34])

In [126]:
np.in1d(arr_only,[11,12])

array([ True,  True, False, False,  True, False,  True])